package com.demonetization.pojo;
// default package
// Generated Apr 23, 2017 11:11:25 AM by Hibernate Tools 5.1.2.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Person generated by hbm2java
 */
@Entity
@Table(name = "person")
public class Person implements java.io.Serializable {

	private Integer id;
	private String firstName;
	private int ssn;
	private String lastName;
	private Set<User> users = new HashSet<User>(0);

	public Person() {
	}

	public Person(String firstName, int ssn, String lastName) {
		this.firstName = firstName;
		this.ssn = ssn;
		this.lastName = lastName;
	}

	public Person(String firstName, int ssn, String lastName, String personcol, Set<User> users) {
		this.firstName = firstName;
		this.ssn = ssn;
		this.lastName = lastName;
		this.users = users;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "FirstName", nullable = false, length = 45)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "SSN", nullable = false)
	public int getSsn() {
		return this.ssn;
	}

	public void setSsn(int ssn) {
		this.ssn = ssn;
	}

	@Column(name = "LastName", nullable = false, length = 45)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@OneToMany( mappedBy = "person")
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

}
