package com.demonetization.pojo;
// default package
// Generated Apr 23, 2017 11:11:25 AM by Hibernate Tools 5.1.2.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ReservationDetails generated by hbm2java
 */
@Entity
@Table(name = "reservation_details")
public class ReservationDetails implements java.io.Serializable {

	private ReservationDetailsId id;
	private Notes notes;
	private Reservation resevation;

	public ReservationDetails() {
	}

	public ReservationDetails(ReservationDetailsId id, Notes notes, Reservation resevation) {
		this.id = id;
		this.notes = notes;
		this.resevation = resevation;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "quantity", column = @Column(name = "Quantity", nullable = false)),
			@AttributeOverride(name = "resevationId", column = @Column(name = "Resevation_id", nullable = false)),
			@AttributeOverride(name = "notesId", column = @Column(name = "Notes_id", nullable = false)) })
	public ReservationDetailsId getId() {
		return this.id;
	}

	public void setId(ReservationDetailsId id) {
		this.id = id;
	}

	@ManyToOne
	@JoinColumn(name = "Notes_id", nullable = false, insertable = false, updatable = false)
	public Notes getNotes() {
		return this.notes;
	}

	public void setNotes(Notes notes) {
		this.notes = notes;
	}

	@ManyToOne
	@JoinColumn(name = "Resevation_id", nullable = false, insertable = false, updatable = false)
	public Reservation getResevation() {
		return this.resevation;
	}

	public void setResevation(Reservation resevation) {
		this.resevation = resevation;
	}

}
