package com.demonetization.pojo;
// default package
// Generated Apr 23, 2017 11:11:25 AM by Hibernate Tools 5.1.2.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ReservationDetailsId generated by hbm2java
 */
@Embeddable
public class ReservationDetailsId implements java.io.Serializable {

	private int quantity;
	private int resevationId;
	private int notesId;

	public ReservationDetailsId() {
	}

	public ReservationDetailsId(int quantity, int resevationId, int notesId) {
		this.quantity = quantity;
		this.resevationId = resevationId;
		this.notesId = notesId;
	}

	@Column(name = "Quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	@Column(name = "Resevation_id", nullable = false)
	public int getResevationId() {
		return this.resevationId;
	}

	public void setResevationId(int resevationId) {
		this.resevationId = resevationId;
	}

	@Column(name = "Notes_id", nullable = false)
	public int getNotesId() {
		return this.notesId;
	}

	public void setNotesId(int notesId) {
		this.notesId = notesId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ReservationDetailsId))
			return false;
		ReservationDetailsId castOther = (ReservationDetailsId) other;

		return (this.getQuantity() == castOther.getQuantity())
				&& (this.getResevationId() == castOther.getResevationId())
				&& (this.getNotesId() == castOther.getNotesId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getQuantity();
		result = 37 * result + this.getResevationId();
		result = 37 * result + this.getNotesId();
		return result;
	}

}
